#! /bin/sh
### BEGIN INIT INFO
# Short-Description: Gammu SMS daemon for Freedom Fone
# Description:       It starts/stop gammu for a given IMSI 
# 		     /etc/init.d/gammu-smsd start <IMSI>
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/gammu-smsd
DESC="Gammu SMS Daemon"
CONFDIR=/opt/freedomfone/gammu-smsd/conf

# user which will run this daemon
USER=gammu

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  show)
  echo "The IMSIs configured for gammu are: "
  cd $CONFDIR
  for s in `ls gammu-smsdrc-*`;do
  	echo $s | sed s/gammu-smsdrc-//
  done
  ;;

  clean)
  echo "Cleaning existing gammu configurations"
  cd $CONFDIR
  for c in `ls gammu-smsdrc-*`;do
  	echo "Disabling $c" | sed s/gammu-smsdrc-//
  mv $c $c.bak
  done 
  ;;
  
start)
  cd $CONFDIR
  for c in `ls gammu-smsdrc-* |grep -v bak`;do
  NAME=$c
  CONF=$CONFDIR/$c
  echo $CONF
    if grep -q '^port = /dev/null' $CONF ; then 
        log_warning_msg " $NAME not yet configured, please edit $CONF"
        exit 0
    fi
	log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON -- -c $CONF --daemon --user $USER \
        --pid /var/run/$NAME.pid
    log_end_msg $?
  done
	;;
  stop)
    cd $CONFDIR
    for t in `ls gammu-smsdrc-* |grep -v bak`;do
    NAME=$t
    CONF=$CONFDIR/$t
    log_daemon_msg "Stopping $DESC" $NAME
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON
    log_end_msg $?
    done
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|show|clean}" >&2
	exit 1
	;;
esac

exit 0

