#!/bin/sh
### BEGIN INIT INFO
# Provides:          gsmopen utils 
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GSMOPEN status  
# Author: Alberto Escudero-Pascual aep@it46.se
### END INIT INFO
##############################################################################

BASEDIR=/usr/local/freedomfone
ESL=$BASEDIR/esl/native
APICLIENT=$ESL/api_client.php
STATUS="gsmopen_dump list"
RELOAD="gsm reload"
PHP=/usr/bin/php
GSMOPEN_BOOT_LOG=/var/tmp/gsmopen_boot.log
AMIXER=/usr/bin/amixer
CARD_LIST="0 1 2"


. /lib/lsb/init-functions


case ${1:-} in
    start)
	log_daemon_msg "Gsmopen, fixing audio levels (waiting 60 seconds)" 
	for i in $CARD_LIST; do
		#$AMIXER -c ${i}  -q set Mic 0% mute
		$AMIXER -c ${i}  -q set Speaker 70% unmute >/dev/null 2>&1
		$AMIXER -c ${i}  -q set Mic cap mute 70%        >/dev/null 2>&1
		$AXIMER -c ${i}  -q set "Auto Gain Control" off >/dev/null 2>&1
	done
		sleep 60
     	set +e
	$PHP $APICLIENT "$STATUS" |grep "imei\|imsi\|interface_id\|interface_name"  
	$PHP $APICLIENT "$STATUS" > $GSMOPEN_BOOT_LOG  
        RC=$?
        set -e
        log_end_msg $RC
      ;;

    status)
		$PHP $APICLIENT "$STATUS"  
    ;;
    reload)
                $PHP $APICLIENT "$RELOAD" |grep reload
   ;;

    *)
      echo "Usage: ${0:-} {start|status}" >&2
      exit 1
    ;;
esac

exit 0

# vim: ai expandtab
